In [41]:
import pandas as pd
import re
import nltk
from nltk import word_tokenize
from collections import Counter
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
import random
from random import randint
from nltk.corpus import stopwords 
from nltk.tokenize import word_tokenize

In [42]:
# Loading the Data
Hotels = pd.ExcelFile("E:/RAAM/GSU MSA/Data Management for Analytics/Final Project/Final.xlsx")
Hotels_List = Hotels.sheet_names

In [43]:
# Finding Nouns used by Customer
cust_review = pd.read_excel("E:/RAAM/GSU MSA/Data Management for Analytics/Final Project/TravelBug0082.xlsx",sheet_name = 'Sheet1').iloc[0,0]

# Removing Stopwords
stop_words = set(stopwords.words('english')) 
x = word_tokenize(cust_review) 
x = [w for w in x if not w in stop_words]



y = nltk.pos_tag(x)

m = []
for i in range(len(y)):
    if y[i][1] == "NN":
        m.append(y[i][0])  
    else:
        pass
    
m.remove('‚Äù')
print(m)

['room', 'clean', 'in/check', 'aircon', 'unit', 'hall', 'work', 'noisy', 'heat', 'bedroom', 'door', 'apartment', 'style', 'room', 'hall', 'bedroom', 'door', 'weather', 'cold', 'imagine', 'heat', 'room', 'summer', 'lobby', 'interesting', 'game', 'room', 'area', 'wood', 'chat', 'restaurant', 'ground', 'floor', 'hotel', 'hotel', 'door', 'conference', 'room', 'shower', 'stall', 'bathroom', 'floor', 'elevator', 'floor', 'office', 'building', 'room', 'work', 'room', 'return', 'day', 'hotel', 'hotel', 'trip', 'visit', 'area', 'walk', 'train', 'station', 'mind', 'tiring', 'day', 'walk', 'get', 'room', 'level', 'ceiling', 'bed', 'size', 'use', 'half', 'glass', 'water', 'floor', 'shower', 'warehouse', 'floor', 'room', 'bar', 'lobby', 'beer', 'area', 'pier', 'bar', 'trailer', 'winter', 'hotel', 'stock', 'visit', 'area', 'hotel', 'convenient', 'location', 'station', 'accessibility', 'cafes', 'room', 'room', 'area', 'shower', 'room', 'didnt', 'control', 'doesnt', 'hotel', 'call', 'change', 'room', 'room', 'phone', 'didnt', 'work', 'repair', 'check', 'ground', 'floor', 'level', 'round', 'table', 'afternoon', 'tea', 'reservation', 'bar', 'stool', 'mushroom', 'fettucine', 'tea', 'afternoon', 'tea', 'king', 'room', 'person', 'shopping', 'family', 'member', 'room', 'cramped', 'table', 'bench', 'touch', 'space', 'part', 'wardrobe', 'space', 'table', 'bathroom', 'day', 'shopping', 'walk', 'cafes', 'size', 'room', 'floor', 'way', 'room', 'reception', 'check', 'in/check', 'gripe', 'airconditioning', 'way', 'temperature', 'mood', 'temperature', 'front', 'entrance', 'shopping', 'access', 'cafes', 'supermarket', 'walk', 'subway', 'hotel', 'acessibility', 'humidifier', 'room', 'buffet', 'breakfast', 'spread', 'night', 'onsen', 'impression', 'area', 'food', 'dinner', 'breakfast', 'breathtaking', 'service', 'bath', 'pool', 'floor', 'area', 'morning', 'bathe', 'bath', 'level', 'gorge', 'walk', 'gorge', 'town', 'evening', 'pearl', 'powder', 'bath', 'skin', 'soak', 'lake', 'furnishing', 'isnt', 'room', 'room', 'quiet', 'spread', 'service', 'attentive', 'hotel', 'subway', 'walk', 'convenient', 'subway', 'way', 'airport', 'morning', 'hour', 'way', 'cab', 'pool', 'lifeguard', 'fancy', 'swim', 'walk', 'hotel', 'pitstop', 'lobby', 'service', 'attentive', 'room', 'bathroom', 'floor', 'get', 'soak', 'day', 'shopping', 'spa', 'table', 'room', 'comfy', 'sofa', 'tv', 'wardrobe', 'housekeeping', 'location', 'convenient', 'walk', 'trams', 'room', 'bed', 'size', 'bathtub/shower', 'curtain/shower', 'combo', 'destination', 'fee', 'night', 'card', 'water', 'list', 'night', 'landing', 'airport', 'evening', 'hotel', 'shuttle', 'hall', 'end', 'terminal', 'wait', 'hotel', 'burger', 'place', 'hotel', 'door', 'shower', 'bed', 'room', 'size', 'area', 'glass', 'stall', 'water', 'shuttle', 'airport', 'convenient', 'conference', 'choice', 'water', 'floor', 'room', 'conference', 'day', 'shower', 'change', 'room', 'hotel', 'pack/unpack', 'airconditioning', 'night', 'issue', 'set', 'design', 'concept', 'get', 'look', 'lobby', 'insist', 'noisy', 'lobby', 'chatter', 'inconsistent', 'year', 'conference', 'hotel', 'water', 'conference', 'week', 'size', 'balcony', 'studio', 'room', 'party', 'room', 'living', 'room', 'pantry', 'hotel', 'room', 'business', 'business', 'district', 'quarter', 'cab', 'car', 'front', 'desk', 'staff', 'style', 'bar', 'pool', 'promotion', 'issue', 'room', 'evening', 'hotel', 'everyone', 'night', 'day', 'wifi', 'plan', 'nothing', 'office', 'area', 'plenty', 'shopping', 'hotel', 'bathroom', 'buffet', 'spread', 'selection', 'tourist', 'place', 'lobby', 'serve', 'tea', 'coffee', 'pastry/cake', 'basement', 'bell', 'staff', 'duty', 'check', 'check', 'luggage', 'standard', 'ole', 'dame', 'conference', 'resort', 'conference', 'resort', 'room', 'living', 'room', 'modernization', 'front', 'desk', 'suite', 'suite', 'bedroom', 'room', 'area', 'balcony', 'pool', 'beach', 'pool', 'area', 'lit', 'night', 'staff', 'time', 'sleep', 'resort', 'issue', 'night', 'conference', 'party', 'area', 'loud', 'band', 'resort', 'rest', 'singing', 'evening', 'night', 'music', 'tune', 'noise', 'peace', 'issue', 'night', 'conference', 'party', 'area', 'loud', 'band', 'resort', 'rest', 'singing', 'evening', 'night', 'music', 'tune', 'noise', 'peace', 'hotel', 'bedroom/bathroom', 'shower', 'work', 'desk', 'wifi', 'mall', 'business', 'holiday']

In [44]:
# Extracting Score of each noun used by customer for every hotel
p = []
for i in range(len(Hotels_List)):
    l = []
    for j in range(len(m)):
        if m[j] in Hotels.parse(i)["Noun"].to_list():
            x = Hotels.parse(i).index[Hotels.parse(i)["Noun"] == m[j]].to_list()[0]
            l.append(Hotels.parse(0).loc[x,"Compound"])
        else:
            l.append(0)
    p.append(l)

In [45]:
# Making a Dataframe
d = {}
for i in range(len(Hotels_List)):
    d.update({Hotels_List[i]:p[i]})
X = pd.DataFrame(d,index = m)

# Rolling upto Unique words
X = X.groupby(X.index).sum()

In [46]:
X

,Aston Islander on the Beach,Coconut Waikiki Hotel,La_Croix,OHANA Waikiki Malia Outrigger,Otani Hotel,Ramada Plaza by Wyndham Waikiki,Sheraton Princess Hotel,Aqua Pacific Monarch
access,0.0,0.000000,0.0,0.599669,0.412929,0.0,0.000000,0.0
accessibility,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0
acessibility,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0
afternoon,0.0,1.155167,0.0,0.000000,0.000000,0.0,0.000000,0.0
aircon,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0
...,...,...,...,...,...,...,...,...
wifi,0.0,0.000000,0.0,0.000000,0.000000,0.0,1.427747,0.0
winter,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0
wood,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0
work,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.0
year,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.603800,0.0

In [47]:
# Ranking and Recommending the Hotel
Scores_sum = X.sum()
Ranking = pd.DataFrame(Scores_sum.sort_values(ascending = False), columns= ["Score"])
Ranking
# Applying Min-Max Scaling
Max = Ranking['Score'].max(axis = 0)
Min = Ranking['Score'].min(axis = 0)
Ranking['Score'] = Ranking['Score'].apply(lambda x:(x - Min)/(Max - Min)*100)
Ranking

                                      Score
Ramada Plaza by Wyndham Waikiki  100.000000
Aqua Pacific Monarch              99.630602
OHANA Waikiki Malia Outrigger     76.210716
Sheraton Princess Hotel           56.826213
Coconut Waikiki Hotel             53.611913
Aston Islander on the Beach       53.063778
Otani Hotel                       32.678532
La_Croix                           0.000000